name: xUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # プロジェクトのバージョンに合わせる

      - name: Restore dependencies
        run: dotnet restore CalculatorApp.Tests/

      - name: Build solution
        run: dotnet build CalculatorApp.Tests/ --no-restore --configuration Release

      - name: Run xUnit tests
        run: dotnet test CalculatorApp.Tests/CalculatorApp.Tests.csproj --no-build --verbosity normal --configuration Release
